### PR TITLE
remove steps obsoleted by new enochecker_test version

### PR DESCRIPTION
**Pull request by ldruschk**

### CODE REVIEW

**Comment by Trolldemorted** [comment]
Don't we need something for the service?

**Comment by ldruschk** [comment]
At the moment there is no way for enochecker_test to do this since it does not have the service port (and the service address might differ from within the checker container and from where enochecker_test is run), but in general I would assume ordering the startups so that the service is started first should allow the startup to complete before the checker build/start is completed, otherwise this seems like something which each service should handle individually via a custom GitHub Actions step (most notably if there are services which expose more than one port or use something else than TCP)

**Comment by Trolldemorted** [comment]
There is no way to do this reliably, but a sleep for 1-2 could satisfy our needs though :)

**Comment by ldruschk** [comment]
I think building/starting the checker takes more than 1-2 seconds :P

**Comment by Trolldemorted** [comment]
Building yes, but that happens during the build stage, so it depends only on how quick a service starts after being built

**Comment by ldruschk** [comment]
I guess, but in this case the checker is built after the service is already started, so that is not relevant to this repository, right?

**Comment by Trolldemorted** [comment]
While we build those sequentially in that order it doesn't matter, yep.

How many cores do we get? Do we consume less CI-minutes if we do more stuff in parallel?

**Comment by ldruschk** [comment]
no idea, but again, this does not seem to be the right place for this discussion

**Pull request merged**
